services:
  sage_backend:
    build:
      context: ../../
      dockerfile: ./examples/fastapi_react_demo/backend/Dockerfile
    container_name: sage_backend
    ports:
      - "20039:8000"  # API服务端口
    volumes:
      - /tmp/sage:/tmp/sage
      - /srv/sage_demo_workspace:/app/workspace  # 工作空间映射
      - ./logs:/app/logs            # 日志映射
    environment:
      - PYTHONUNBUFFERED=1
      - WORKSPACE_ROOT=/app/workspace
      - DOCKER_ENV=true
      - SAGE_CONFIG_FILE=/app/examples/fastapi_react_demo/backend/config.yaml
      # AList 环境变量
      - ALIST_ENDPOINT=sage_alist:5244
      - ALIST_USERNAME=admin
      - ALIST_PASSWORD=sage123456
      - WORKSPACE_PATH=/app/workspace
    depends_on:
      sage_alist:
        condition: service_started
    restart: unless-stopped

  sage_frontend:
    build:
      context: ../../
      dockerfile: ./examples/fastapi_react_demo/frontend/Dockerfile
    container_name: sage_frontend
    ports:
      - "20040:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - sage_backend
    restart: unless-stopped

  # AList 文件服务
  sage_alist:
    image: docker.m.daocloud.io/xhofe/alist:latest
    container_name: sage_alist
    ports:
      - "20045:5244"      # AList Web 界面端口
    volumes:
      - /srv/sage_demo_workspace:/opt/alist/data/workspace  # 工作空间直接映射
      - ./alist-data:/opt/alist/data    # AList 配置和数据
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    restart: unless-stopped
    command: |
      sh -c "
        # 确保数据目录存在
        mkdir -p /opt/alist/data
        
        # 首次启动设置密码（检查数据库是否存在）
        if [ ! -f /opt/alist/data/data.db ]; then
          echo '设置管理员密码...'
          /opt/alist/alist admin set sage123456 --data /opt/alist/data
        fi
        
        # 启动AList服务
        echo '启动AList服务...'
        /opt/alist/alist server --data /opt/alist/data
      "