version: '3.8'

services:
  sage_backend:
    build:
      context: ../../
      dockerfile: ./examples/fastapi_react_demo/backend/Dockerfile
    container_name: sage_backend
    ports:
      - "20039:8000"
    volumes:
      - /tmp/sage:/tmp/sage
    command: "python main.py"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - sage_frontend

  sage_frontend:
    build:
      context: ../../
      dockerfile: ./examples/fastapi_react_demo/frontend/Dockerfile
    container_name: sage_frontend
    ports:
      - "20040:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true