version: '3.8'

services:
  backend:
    build:
      context: ../../
      dockerfile: ./examples/fastapi_react_demo/backend/Dockerfile
    container_name: sage_backend
    ports:
      - "40039:8000"
    command: "python main.py"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - frontend

  frontend:
    build:
      context: ../../
      dockerfile: ./examples/fastapi_react_demo/frontend/Dockerfile
    container_name: sage_frontend
    ports:
      - "40040:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true